run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused constants, variables, functions
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Spell checker
    - revive        # Replacement for golint
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - gosec         # Security checker
    - bodyclose     # Check HTTP response body closed
    - errorlint     # Find code that will cause problems with error wrapping
    - gocyclo       # Cyclomatic complexity
    - funlen        # Function length checker
    - gocognit      # Cognitive complexity

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment  # Can be too strict for readability

  gofmt:
    simplify: true

  goimports:
    local-prefixes: goarchive

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false

  gosec:
    excludes:
      - G204  # Subprocess launched with variable - needed for pg_dump/pg_restore
      - G304  # File path provided as taint input - expected for backup operations

  gocyclo:
    min-complexity: 15

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 20

  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude some linters for test files
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - gocognit
        - gosec
    # Allow main packages to omit package comments  
    - path: cmd/
      linters:
        - revive
      text: "package-comments"
    # Allow examples to be simpler
    - path: examples/
      linters:
        - errcheck
        - gosec
    # Ignore vendor and templates
    - path: (vendor|_templates)/
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0
