coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false

ignore:
  - "examples/**"
  - "_templates/**"
  - "**/*_test.go"
  - "cmd/goarchive/main.go"
